'use client';

import { ScrollText } from 'lucide-react';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';

export default function StatementsPage() {
  return (
    <div className="container max-w-4xl mx-auto py-8 px-4 space-y-6">
      <div className="flex items-center gap-3 mb-2">
        <ScrollText className="h-8 w-8 text-primary" />
        <div>
          <h1 className="text-3xl font-bold">Investment Statements &amp; Disclosures</h1>
          <p className="text-muted-foreground text-sm mt-1">Last updated: January 2025</p>
        </div>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>1. Risk Disclosures</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-muted-foreground space-y-2">
          <p>
            All investments involve risk, including the possible loss of principal. Past performance
            is not indicative of future results. The value of investments and the income derived from
            them may fluctuate, and investors may not recover the amounts originally invested.
          </p>
          <p>
            Market conditions, interest rates, economic factors, and other variables can affect the
            performance of any investment. Investors should carefully consider their investment
            objectives, risk tolerance, time horizon, and financial situation before making any
            investment decisions.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>2. Investment Disclaimers</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-muted-foreground space-y-2">
          <p>
            The information provided through this platform is for informational and analytical
            purposes only. It does not constitute an offer to buy or sell any security, financial
            product, or instrument. All analysis, ratings, and scores generated by this platform
            are based on the data provided and the analytical models applied at the time of
            calculation.
          </p>
          <p>
            TCA (Total Capital Allocation) and IRR (Internal Rate of Return) scores are proprietary
            analytical outputs and should be interpreted in the context of the specific company and
            industry being analyzed. These scores are not guarantees of future performance or
            investment outcomes.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>3. No Financial Advice</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-muted-foreground space-y-2">
          <p>
            Nothing contained in this platform constitutes investment, legal, tax, or other
            professional advice. You should consult with a qualified financial advisor, attorney,
            or tax professional before making any investment or financial decisions.
          </p>
          <p>
            The analytical tools and reports provided are intended to supplement, not replace,
            independent professional judgment and due diligence. Users are solely responsible for
            their investment decisions.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>4. Regulatory Compliance</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-muted-foreground space-y-2">
          <p>
            This platform is designed to assist with financial analysis in compliance with
            applicable regulations and industry standards. Users are responsible for ensuring
            their use of the platform and any reports generated comply with all applicable laws,
            regulations, and professional standards in their jurisdiction.
          </p>
          <p>
            Investment analysis frameworks referenced in this platform, including IRR and capital
            allocation methodologies, are applied in accordance with generally accepted financial
            analysis principles. Users should ensure their reporting obligations are met
            independently.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>5. Data Sources Statement</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-muted-foreground space-y-2">
          <p>
            Financial data used in analyses may be sourced from company filings, publicly available
            financial statements, third-party data providers, and user-supplied inputs. While we
            strive to ensure accuracy, we make no representations or warranties regarding the
            completeness, accuracy, or timeliness of any data.
          </p>
          <p>
            Users who supply their own financial data are responsible for its accuracy and
            completeness. Analytical outputs are only as reliable as the underlying data inputs.
            TCA-IRR does not independently verify user-submitted financial information.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>6. Forward-Looking Statements</CardTitle>
        </CardHeader>
        <CardContent className="prose prose-sm max-w-none text-muted-foreground space-y-2">
          <p>
            Certain analyses, projections, and reports generated by this platform may contain
            forward-looking statements. These statements are based on current expectations,
            estimates, and assumptions, and are subject to risks and uncertainties that could
            cause actual results to differ materially from those projected.
          </p>
          <p>
            Forward-looking statements are not guarantees of future performance. Actual events and
            circumstances may differ from those described in any forward-looking statements.
            Users should not place undue reliance on forward-looking projections when making
            investment decisions.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
