import { config } from 'dotenv';
config();

import '@/ai/flows/assess-macro-trend-alignment.ts';
import '@/ai/flows/generate-tca-scorecard.ts';
import '@/ai/flows/generate-risk-flags-and-mitigation.ts';
import '@/ai/flows/generate-benchmark-comparison.ts';
import '@/ai/flows/generate-comprehensive-analysis.ts';
import '@/ai/flows/generate-growth-classifier';
import '@/ai/flows/generate-gap-analysis';
import '@/ai/flows/generate-founder-fit-analysis';
import '@/ai/flows/generate-team-assessment';
import '@/ai/flows/generate-strategic-fit-matrix';
import '@/ai/flows/generate-financial-analysis';
import '@/ai/flows/generate-economic-analysis';
import '@/ai/flows/generate-social-analysis';
import '@/ai/flows/generate-marketing-analysis';
import '@/ai/flows/generate-environmental-analysis';
import '@/ai/flows/generate-funder-analysis';
import '@/ai/flows/generate-strategic-analysis';
